### ISSUE TITLE
I cant load MindMax database

### ISSUE THREAD

**Issue by tranvictor** [appliedsec/pygeoip#80]
I downloaded and tried with both GeoLite2 CSV and MMDB database file but nothing worked.
The error is:

```
Traceback (most recent call last):
  File "test.py", line 71, in <module>
    benchmark_pygeoip()
  File "test.py", line 61, in benchmark_pygeoip
    g.country_name_by_addr(ip)
  File "/Library/Python/2.7/site-packages/pygeoip/__init__.py", line 488, in country_name_by_addr
    country_id = self.id_by_addr(addr)
  File "/Library/Python/2.7/site-packages/pygeoip/__init__.py", line 422, in id_by_addr
    return self._seek_country(ipnum) - const.COUNTRY_BEGIN
  File "/Library/Python/2.7/site-packages/pygeoip/__init__.py", line 241, in _seek_country
    raise GeoIPError('Corrupt database')
pygeoip.GeoIPError: Corrupt database
```

**Comment by oschwald** [comment]
You need to use the [GeoLite Legacy binary databases](http://dev.maxmind.com/geoip/legacy/geolite/) with pygeoip. If you want to use the GeoLite2 MMDB databases, you could try [geoip2](https://github.com/maxmind/GeoIP2-python).
